name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          ./build_fonts.sh
          zip -r fonts fonts
      - uses: actions/upload-artifact@v2
        with:
          name: fonts.zip
          path: fonts.zip

  release-github:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Artifacts
        uses: actions/download-artifact@v2
      - name: Create GitHub Release
        if: github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v')
        run: gh release create "${GITHUB_REF#refs/tags/}" fonts.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
